<?php

use Illuminate\Database\Seeder;

class EventsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('events')->insert(array (
  0 => 
  array (
    'id' => 1,
    'event' => 'Pongal',
    'seo_url' => 'pongol',
    'image_url' => 'pongal.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 1,
    'created_at' => '2017-02-27 09:47:30',
    'updated_at' => '2017-03-22 17:57:51',
  ),
  1 => 
  array (
    'id' => 2,
    'event' => 'Republic Day',
    'seo_url' => 'republic-day',
    'image_url' => 'republicday.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:30',
    'updated_at' => '2017-02-27 09:47:30',
  ),
  2 => 
  array (
    'id' => 3,
    'event' => 'Holi',
    'seo_url' => 'holi',
    'image_url' => 'holi.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:30',
    'updated_at' => '2017-02-27 09:47:30',
  ),
  3 => 
  array (
    'id' => 4,
    'event' => 'Ugadi',
    'seo_url' => 'ugadi',
    'image_url' => 'ugadi.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:30',
    'updated_at' => '2017-02-27 09:47:30',
  ),
  4 => 
  array (
    'id' => 5,
    'event' => 'Ramzan',
    'seo_url' => 'ramjan',
    'image_url' => 'ramzan.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:30',
    'updated_at' => '2017-02-27 09:47:30',
  ),
  5 => 
  array (
    'id' => 6,
    'event' => 'Easter',
    'seo_url' => 'easter',
    'image_url' => 'easter.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:30',
    'updated_at' => '2017-02-27 09:47:30',
  ),
  6 => 
  array (
    'id' => 7,
    'event' => 'Raksha Bandhan',
    'seo_url' => 'rakshabandhan',
    'image_url' => 'rakshabandan.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:31',
    'updated_at' => '2017-02-27 09:47:31',
  ),
  7 => 
  array (
    'id' => 8,
    'event' => 'Ganesh Chaturthi',
    'seo_url' => 'ganeshchaturthi',
    'image_url' => 'ganeshchaturthi.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:31',
    'updated_at' => '2017-02-27 09:47:31',
  ),
  8 => 
  array (
    'id' => 9,
    'event' => 'Bakrid',
    'seo_url' => 'bakrid',
    'image_url' => 'bakrid.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:31',
    'updated_at' => '2017-02-27 09:47:31',
  ),
  9 => 
  array (
    'id' => 10,
    'event' => 'New Year',
    'seo_url' => 'newyear',
    'image_url' => 'newyear.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:31',
    'updated_at' => '2017-02-27 09:47:31',
  ),
  10 => 
  array (
    'id' => 11,
    'event' => 'Valentines Day',
    'seo_url' => 'valentinesDay',
    'image_url' => 'valentinesday.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:31',
    'updated_at' => '2017-02-27 09:47:31',
  ),
  11 => 
  array (
    'id' => 12,
    'event' => 'Dussehra',
    'seo_url' => 'dussehra',
    'image_url' => 'dussehra.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:31',
    'updated_at' => '2017-02-27 09:47:31',
  ),
  12 => 
  array (
    'id' => 13,
    'event' => 'Diwali',
    'seo_url' => 'diwali',
    'image_url' => 'diwali.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:31',
    'updated_at' => '2017-02-27 09:47:31',
  ),
  13 => 
  array (
    'id' => 14,
    'event' => 'Merry Christmas',
    'seo_url' => 'marrychristmas',
    'image_url' => 'chirstmas.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:31',
    'updated_at' => '2017-02-27 09:47:31',
  ),
  14 => 
  array (
    'id' => 15,
    'event' => 'Independence day',
    'seo_url' => 'independenceday',
    'image_url' => 'independenceday.jpg',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-27 09:47:31',
    'updated_at' => '2017-02-27 09:47:31',
  ),
  15 => 
  array (
    'id' => 16,
    'event' => 'holi',
    'seo_url' => 'http://diwali.com',
    'image_url' => '',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-28 10:02:58',
    'updated_at' => '2017-02-28 10:02:58',
  ),
  16 => 
  array (
    'id' => 17,
    'event' => 'holi',
    'seo_url' => 'http://diwali.com',
    'image_url' => '',
    'meta_title' => '',
    'meta_description' => '',
    'meta_keywords' => '',
    'h1' => '',
    'h2' => '',
    'c_uid' => 0,
    'u_uid' => 0,
    'created_at' => '2017-02-28 10:03:09',
    'updated_at' => '2017-02-28 10:03:09',
  ),
));
    }
}
