@extends('layouts.master') 

@section('meta_title') {{ $data['meta']->meta_title }} @endsection
@section('meta_description') {{ $data['meta']->meta_description }} @endsection
@section('meta_keywords') {{ $data['meta']->meta_keywords }} @endsection
@section("robots")
	@if($data['meta']->robots==1)
		<meta name="robots" content="index, follow">
	@else
		<meta name="robots" content="noindex, nofollow">
	@endif
@endsection


@section('content')
<div class="container-fluid">
    <h1 class="text-center">Terms Of Use</h1>
    <div class="col-md-10 col-md-offset-1">
        <h2>VoucherToPay, UK Terms of Use</h2>
        <p class="text-justify">This web page represents a legal document that serves as our Terms of Use. It governs the legal terms of our website, http://www.vouchertopay.com/, sub-domains, and any associated web-based applications (collectively, "VoucherToPay"), as owned and operated by VoucherToPay, UK.</p>
        <p class="text-justify">Capitalized terms, unless otherwise defined, have the meaning specified within the definitions section below. This Terms of Use, along with our Privacy Policy, any mobile license agreement, and other posted guidelines within our Website, collectively "Legal Terms", constitute the entire and only agreement between you and VoucherToPay, and supersede all other agreements, representations, warranties, and understandings with respect to our Website and the subject matter contained therein. We may amend our Legal Terms at any time without specific notice to you. The latest copies of our Legal Terms will be posted on our Website, and you should review all Legal Terms prior to using our Website. After any revisions to our Legal Terms are posted, you agree to be bound to any such changes to them. Therefore, it is important for you to periodically review our Legal Terms to make sure you still agree to them.</p>
        <p class="text-justify">By using our Website, you agree to fully comply with and be bound by our Legal Terms. Please review them carefully. If you do not accept our Legal Terms, do not access and use our Website. If you have already accessed our Website and do not accept our Legal Terms, you should immediately discontinue use of our Website.</p>
        <p class="text-justify">The last update to our Terms of Use was posted on Feb-10-2017</p>
        <h2>Definitions</h2>
        <p class="text-justify">The terms "us" or "we" or "our" or "Site" refer to VoucherToPay, the owner of the Website.</p>
        <p class="text-justify">A "Visitor" is someone who merely browses our Website, but has not registered as Member.</p>
        <p class="text-justify">A "Member" is an individual that has registered with us to use our service.</p>
        <p class="text-justify">Our "Service" represents the collective functionality and features as offered through our Website to our Members.</p>
        <p class="text-justify">A "User" is a collective identifier that refers to either a Visitor or a Member.</p>
        <p class="text-justify">All text, information, graphics, audio, video, and data offered through our Website are collectively known as our "Content".</p>
        <h2>Conditions of Services</h2>
        <p class="text-justify">VoucherToPay does not offer any warranties for vouchers and discounts or any product offered by merchants or individuals. The site is not responsible for the quality, accuracy, timeliness, reliability or any other aspect of these products and services. VoucherToPay makes no representation that the Site is available for use in your location, and a reference to Services within the site does not imply that the services will be available to you and/or in your location. The services offered on or through the site may change at any time without any prior notice by VoucherToPay.</p>
        <h2>Legal Compliance</h2>
        <p class="text-justify">You agree to comply with all applicable domestic and international laws, statutes, ordinances, and regulations regarding your use of our Website. VoucherToPay reserves the right to investigate complaints or reported violations of our Legal Terms and to take any action we deem appropriate, including but not limited to canceling your Member account, reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties and disclosing any information necessary or appropriate to such persons or entities relating to your profile, email addresses, usage history, posted materials, IP addresses and traffic information, as allowed under our Privacy Policy.</p>
        <h2>IP Rights</h2>
        <p class="text-justify">Our Website may contain our service marks or trademarks as well as those of our affiliates or other companies, in the form of words, graphics, and logos. Your use of our Website does not constitute any right or license for you to use such service marks/trademarks, without the prior written permission of the corresponding service mark/trademark owner. Our Website is also protected under international copyright laws. The copying, redistribution, use or publication by you of any portion of our Website is strictly prohibited. Your use of our Website does not grant you ownership rights of any kind on our Site.</p>
        <h2>Our Terms for Your Conduct</h2>
        <p class="text-justify">This site makes use of Robot exclusion headers. The site doesn't grant you permission to use any robot, spider, scraper or other automated means to access VoucherToPay.com for any purpose without our express written permission.</p>
        <p class="text-justify">You agree not to reproduce, duplicate, copy, sell, resell or exploit for any commercial purposes, any portion of the Site, use of the Site, or access to the Site.</p>
        <p class="text-justify">You agree not to access the Site by any means other than through the interface that is provided by us for use in accessing the Site.</p>
        <p class="text-justify">You agree not to bypass our robot exclusion headers or other measures we may use to prevent or restrict access to the Site.</p>
        <h2>General Terms</h2>
        <p class="text-justify">Our Legal Terms shall be treated as though it were executed and performed in the U.K., and shall be governed by and construed in accordance with the laws U.K, without regard to conflict of law principles. In addition, you agree to submit to the personal jurisdiction and venue of such courts. Any cause of action by you with respect to our Website, must be instituted within one (1) year after the cause of action arose or be forever waived and barred. Should any part of our Legal Terms be held invalid or unenforceable, that portion shall be construed consistent with applicable law and the remaining portions shall remain in full force and effect. To the extent that any Content in our Website conflicts or is inconsistent with our Legal Terms, our Legal Terms shall take precedence. Our failure to enforce any provision of our Legal Terms shall not be deemed a waiver of such provision nor of the right to enforce such provision. The rights of VoucherToPay under our Legal Terms shall survive the termination of our Legal Terms.</p>
        <h2>Indemnity</h2>
        <p class="text-justify">You agree to indemnify and hold us, and our subsidiaries, affiliates, directors, officers, agents, vendors or other partners and employees harmless from any claim or demand, including attorneys' fees, made by any third party due to or arising out of any material or information posted, provided, transmitted or otherwise made available by you on the Site or through the Site's services, or by your violation of these Terms and Conditions, or by your violation of the rights of another.</p>
        <h2>Feedback</h2>
        <p class="text-justify">All comments or materials submitted by you to VoucherToPay through the site or social media websites, including without limitation, feedback, testimonials, images, reviews, questions, comments, ideas, or suggestions (collectively, "Feedback") shall be received and treated by VoucherToPay on a non-confidential and unrestricted basis. </p>
        <p class="text-justify">Further, VoucherToPay shall be free to use, copy, display, perform, distribute, adapt, and promote, in any medium now known or later developed, without compensation to you, the Feedback along with all ideas, concepts, know-how, techniques or methodologies contained in such feedback, for any purpose whatsoever, including without limitation, developing, marketing and selling products and/or services incorporating such Feedback. You agree that in submitting feedback, it will not violate these Terms of Use or any right of any third party, including without limitation, any confidentiality, copyright, trademark, privacy or other personal or intellectual property or proprietary rights, and will not cause injury to any person or entity. </p>
        <p class="text-justify">You further agree that no Feedback you submit will be or contain libelous or otherwise unlawful, threatening, abusive or obscene material, or contain viruses, commercial solicitations, or any form of "spam". VoucherToPay may, in its sole discretion, remove any Feedback you submit to the Site that in its opinion breaches these Terms of Use or any applicable law, or is otherwise objectionable.</p>
        <h2>This Website- Simply a Podium</h2>
        <p class="text-justify">This Web site acts as a mere podium for displaying the vouchers and discounts. We do not take part in the actual transaction that takes place between the buyers and sellers and hence are not a party to any contract for sale negotiated between buyers and sellers.</p>
        <h2>User(S) Eligibility</h2>
        <p class="text-justify">User(s) means any individual or business entity/organization that legally operates in UK or in other countries, uses and has the right to use the services provided by VoucherToPay. Our services are available only to those individuals or companies who can form legally binding contracts under the applicable law. Therefore, user(s) must not be a minor as per applicable Law; i.e. user(s) must be at least 18 years of age to be eligible to use our services.</p>
        <h2>Managing Accounts</h2>
        <p class="text-justify">Subject to the terms and conditions under this agreement, a user can create his/ her account as per the convenience by following the directions on the Site for registering and opening a user account. Your user account shall contain your profile and other personal information. Users of VoucherToPay are limited to one VoucherToPay account per user. Users who are found to be in violation of this policy, we will delete the account. Only you shall have control over your VoucherToPay profile. You should keep your User Account information confidential. Under no circumstances is it appropriate, and it shall be strictly prohibited for you or anyone else to use another user's User Account. If you feel that your profile or User Account has been compromised in any way, or if there has been any unauthorized use of your User Account, you must notify us immediately. </p>
        <p class="text-justify">As further set forth in this agreement, you agree to hold VoucherToPay free from any liability pertaining to any losses whatsoever that may occur in the event that any unauthorized third party shall use or access your User Account or profile in any way. Please be aware that we reserve the right to interrupt your service, access your User Account and/or access to the Site or any services or products we offer, with or without prior notice, for any reason, at our sole and absolute discretion. In the event, your user account is interrupted or terminated for any reason, whether intentionally or unintentionally, we will not be liable for any losses due in whole or in part by such interruption or termination of the user account. You hereby agree to hold us irresponsible from any such losses which you may suffer as a result of or in any way related to such interruption or termination.</p>
        <h2>IP Address</h2>
        <p class="text-justify">An IP address is a number that is automatically assigned to your computer when you surf the Internet. When you request pages from our web sites, the web server automatically logs your IP address. VoucherToPay may use the log for systems administration. Whenever the confirmation link is clicked from email, VoucherToPay holds the IP address of the user's PC for contest selection purpose.</p>
        <p class="text-justify">Children Online Protection Act Notification:</p>
        <p class="text-justify">We hereby notify you that parental control protections (such as computer hardware, software, or filtering services) are commercially available that may assist you in limiting access to material that is harmful to minors.</p>
        <h2>Digital Millennium Copyright Act Policy:</h2>
        <p class="text-justify">VoucherToPay, Inc. ("VoucherToPay") supports the protection of intellectual property and asks the users of the website VoucherToPay.com to do the same. </p>
        <p class="text-justify">Notice is specifically given that VoucherToPay is not responsible for the content on other websites that any user may find or access when using VoucherToPay.com. This notice describes the information that should be provided in notices alleging copyright infringement found specifically on VoucherToPay.com, and this notice is designed to make alleged infringement notices to VoucherToPay as straightforward as possible and, at the same time, minimize the number of notices that VoucherToPay receives that are spurious or difficult to verify. </p>
        <p class="text-justify">It is the policy of VoucherToPay, in appropriate circumstances and in its sole discretion, to disable and/or terminate the accounts of users of VoucherToPay.com who may infringe upon the copyrights or other intellectual property rights of VoucherToPay and/or others.</p>
        <p class="text-justify">Our response to a notice of alleged copyright infringement may result in removing or disabling access to material claimed to be a copyright infringement and/or termination of the subscriber. If VoucherToPay removes or disables access in response to such a notice, we will make a reasonable effort to contact the responsible party of our decision so that they may make an appropriate response.</p>
        <p class="text-justify">To file a notice of an alleged copyright infringement with us, you are required to provide a written communication only by email or postal mail. Notice is also given that you may be liable for damages (including costs and attorney fees) if you materially misrepresent that a product or activity is infringing upon your copyright.</p>
        <h2>Copyright Grievance</h2>
        <p class="text-justify">We respect the intellectual property of others, and we ask our users to do the same. If you believe that your work has been copied and is accessible on the Site in a way that constitutes copyright infringement, you may notify us by providing our copyright agent the following information:</p>
        <p class="text-justify">An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest.</p>
        <p class="text-justify">A description of the copyrighted work that you claim has been infringed, including the URL (i.e., web page address) of the location where the copyrighted work exists or a copy of the copyrighted work.</p>
        <p class="text-justify">Identification of the URL or other specific location on the Site where the material that you claim is infringing is located.</p>
        <p class="text-justify">Your address, telephone number, and email address.</p>
        <p class="text-justify">A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law.</p>
        <p class="text-justify">A statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.</p>
        <p class="text-justify">Our agent for notice of claims of copyright infringement on the Site can be reached by Support@VoucherToPay.com</p>
        <h2>Disclaimers</h2>
        <p class="text-justify">This entire site content provided by VoucherToPay is only for informational and entertainment purposes. Our linking to such third-party sites does not imply an endorsement or sponsorship of such sites, or the information, products or services offered on or through the sites. In addition, neither we nor our parent or subsidiary companies nor any of our respective affiliates operate or control in any respect any information, products or services that third parties may provide on or through the Site or on websites linked to by us on the Site. VoucherToPay has no control over the legal documents and privacy practices of third party websites; as such, you access any such third party websites at your own risk.</p>
        <p class="text-justify">THE INFORMATION, PRODUCTS AND SERVICES OFFERED ON OR THROUGH THE SITE AND ANY THIRD-PARTY SITES ARE PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. WE DO NOT WARRANT THAT THE SITE OR ANY OF ITS FUNCTIONS WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT ANY PART OF THIS SITE, INCLUDING BULLETIN BOARDS, OR THE SERVERS THAT MAKE IT AVAILABLE, ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>
        <p class="text-justify">WE DO NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE SITE OR MATERIALS ON THIS SITE OR ON THIRD-PARTY SITES IN TERMS OF THEIR CORRECTNESS, ACCURACY, TIMELINESS, RELIABILITY OR OTHERWISE.</p>
        <p class="text-justify">You must provide and are solely responsible for all hardware and/or software necessary to access the Site. You assume the entire cost of and responsibility for any damage to, and all necessary maintenance, repair or correction of, that hardware and/or software.</p>
        <p class="text-justify">The Site is provided for informational purposes only, and is not intended for trading or investing purposes, or for commercial use. The Site should not be used in any high risk activities where damage or injury to persons, property, environment, finances or business may result if an error occurs. You expressly assume all risk for such use.</p>
    </div>
</div>
@endsection
